#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import threading

# lors d'une connexion avec le serveur
# le reseau envoi la chaine de caractere "\nBienvenue\n" au client
# si la connexion est de type IA on envoie "IA" au serveur
# si la connexion est de type Display on envoie "DISPLAY" au serveur

host = ''
team = 0
port = 0

def	check_args():
	global host
	global team
	global port
	s = ''
	host = 'localhost'
	if (len(sys.argv) == 5 or len(sys.argv) == 7):
		i = 1
		while i < len(sys.argv):
			if sys.argv[i] == "-n":
				team = int(sys.argv[i + 1])
				s = s + "-n " + str(team) + " "
			elif sys.argv[i] == "-h":
				host = sys.argv[i + 1]
				s = s + "-h " + host + " "
			elif sys.argv[i] == "-p":
				port = int(sys.argv[i + 1])
				s = s + "-p " + str(port) + " "
			i = i + 2
	else:
		print "USAGE: ./Client [-h hote] [-n equipe] [-p port]"
		exit()
	return s

def	launchDisplay(s):
	c = "./Display " + s
	os.system(c)

def	launchIA(s):
	print "IA"
	#os.system()

def	main():
    try:
	s = check_args()
	launchDisplay(s)
	#a = threading.Thread(None, launchDisplay, None, (s,), {})
	#b = threading.Thread(None, launchIA, None, (s,), {})
	#a.start()
	#b.start()
	#a.Thread.__stop__()
	#b.Thread.__stop__()
    except IOError: exit(1)
main()
