#!/usr/bin/python


import sys
from socket import *
import sfml as sf
from net import Net
from window import *
from map import *

def     initConnexion(net):
    try:
        net._sock = socket(AF_INET, SOCK_STREAM)
        net._sock.connect((net._host, net._port))
        chaine = "Bienvenue\n"
        net._sock.send(chaine)
    except socket:
        print "Pas de connexion au serveur"
        exit()

def	check_args(net):
    if (len(sys.argv) == 5 or len(sys.argv) == 7):
	i = 1
        while i < len(sys.argv):
            if sys.argv[i] == "-n":
                net._team = int(sys.argv[i + 1])
            elif sys.argv[i] == "-h":
                net._host = sys.argv[i + 1]
	    elif sys.argv[i] == "-p":
                net._port = int(sys.argv[i + 1])
            i = i + 2
    else:
	print "USAGE: ./Client [-h hote] [-n equipe] [-p port]"
	exit()

def	main():
    try:
        # prendre les arguments du server pour la taille de la map
        net = Net()
	check_args(net)
        initConnexion(net)
        #tailleX = sys.argv[1]
        #tailleY = sys.argv[2]
        print "Nom d'equipe: " + str(net._team)
	print "Hote: " + net._host
	print "Port: " + str(net._port)
        #w = Windows(tailleX, tailleY)
        #w.CheckClose()
        #net._sock.close()
    except IOError: exit(1)

main()


# -*- coding: utf-8 -*-
