#!/usr/bin/python

import	sfml as sf
import	socket
import  time
import	sys

def	    music():
#play music
    music = sf.Music.from_file("ressources/contact.wav")
    music.play()

def     getPosMouse():
    if sf.Mouse.is_button_pressed(sf.Mouse.LEFT):
        position = sf.Mouse.get_position()
    return position

def	    gereMouse(window):
    if sf.Mouse.is_button_pressed(sf.Mouse.LEFT):
        position = sf.Mouse.get_position()
        window.draw(drawText("Case Numero x -- \n\nInfo 1 :\tToto\nInfo2 :\t" +
            "Tutu\nInfo3 :\t Titi", 20, 480, 100))

def     checkCase():
    # tab = []
    # tab = drawMap()
    # position = getPosMouse()
    # while tab:
    #     if (position.x < tab[i])


def     drawRectangle(pos):
    paddle_size = sf.Vector2(50, 50)
    rectangle = sf.RectangleShape()
    rectangle.size = paddle_size - (3, 3)
    rectangle.outline_thickness = 1
    rectangle.outline_color = sf.Color.RED
    rectangle.fill_color = sf.Color.GREEN
    rectangle.move(pos)
    return rectangle

def	drawText(msg, size, pos_x, pos_y):
    font = sf.Font.from_file("ressources/Sansation_Bold.ttf")
    instructions = sf.Text(msg, font, size)
    instructions.position = (pos_x, pos_y)
    instructions.color = sf.Color(80, 80, 80)
    return instructions

def	drawMap():
    tab1 = []
    tab = []
    position_x = 0
    position_y = 0
    paddle_size = sf.Vector2(20, 20)
    while position_y <= 400:
        position_x = 0
        while position_x <= 400:
            tab.append(drawRectangle(sf.Vector2(position_x, position_y)))
	    position_x += 50
	position_y += 50
    return tab

def     mainWindow():
    drawmap = []
    drawmap = drawMap()
    # sf.Style.FULLSCREEN
    window = sf.RenderWindow(sf.VideoMode(800, 600), "Client")
    while window.is_open:
	for event in window.events:
	    if type(event) is sf.CloseEvent:
		window.close()
	    if type(event) is sf.KeyEvent and event.code is sf.Keyboard.ESCAPE:
		window.close()
	window.clear()
	for i in range(0, len(drawMap())):
	    window.draw(drawmap[i])
        if gereMouse(window):
            window.display()
	#window.draw(drawText("C'est le zappy pipi de chameau !!", 20, 150, 500))
        window.display()

def	init_connect():
    HOST = "localhost"
    if (len(sys.argv) == 5):
        i = 1
        while i < len(sys.argv):
            if sys.argv[i] == "-n":
                TEAM = sys.argv[i + 1]
	    elif sys.argv[i] == "-p":
                PORT = int(sys.argv[i + 1])
            i = i + 2
 	print "Nom d'equipe: " + TEAM
	print "Hote: " + HOST
	print "Port: " + str(PORT)
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	try:
	    sock.connect((HOST, PORT))
	except socket.error:
	    exit()
	print "Connexion etablie avec le serveur"
	query = "Yoooo C'est le Rap du Ratz !!"
	sock.send(query)
    elif (len(sys.argv) == 7):
	i = 1
        while i < len(sys.argv):
            if sys.argv[i] == "-n":
                TEAM = sys.argv[i + 1]
            elif sys.argv[i] == "-h":
                HOST = sys.argv[i + 1]
	    elif sys.argv[i] == "-p":
                PORT = int(sys.argv[i + 1])
            i = i + 2
	print "Nom d'equipe: " + TEAM
	print "Hote: " + HOST
	print "Port: " + str(PORT)
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	try:
	    sock.connect((HOST, PORT))
	except socket.error:
	    exit()
	print "Connexion etablie avec le serveur"
	query = "Yoooo C'est le Rap du Ratz !!"
	sock.send(query)
    else:
	print "USAGE: ./Client [-h hote] [-n equipe] [-p port]"
	exit()

def	main():
    try:
	#init_connect()
	music()
	mainWindow()
    except IOError: exit(1)
main()