#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from socket import *
import sfml as sf
from net import *
from window import *
from map import *
from evoly import *
from perso import *

def     initConnexion(net):
    try:
        net._sock = socket(AF_INET, SOCK_STREAM)
        net._sock.connect((net._host, net._port))
        chaine = "DISPLAY\n"
        net._sock.send(chaine)
    except socket:
        print "Pas de connexion au serveur"
        exit()

def	check_args(net):
    if (len(sys.argv) == 5 or len(sys.argv) == 7):
	i = 1
        while i < len(sys.argv):
            if sys.argv[i] == "-n":
                net._team = int(sys.argv[i + 1])
            elif sys.argv[i] == "-h":
                net._host = sys.argv[i + 1]
	    elif sys.argv[i] == "-p":
                net._port = int(sys.argv[i + 1])
            i = i + 2
    else:
	print "USAGE: ./Client [-h hote] [-n equipe] [-p port]"
	exit()

def	main():
    try:
        net = Net()
	check_args(net)
        initConnexion(net)
        print "Nom d'equipe: " + str(net._team)
	print "Hote: " + net._host
	print "Port: " + str(net._port)
        # recuperation bienvenue
        data = net._sock.recv(1024)
        if data == "Bienvenue":
            print "Bienvenue"
        else:
            print "Problème lors de l'initialisation du client"
            net._sock.close()
            exit()
        #recuperation taille de la map
        w = recup_sizeMap(net)
        # demande de l'unite de temps au serveur
        askForTimeUnit(net)
        # recuperation de toutes les ressources contenues dans chaque case aupres du serveur
        recup_mapContent(net)
                
        net._sock.close()
    except IOError: exit(1)

main()


#recuperation du nombre de client qui peuvent encore se connecter
        #si le nombre est superieur ou egal a 1 on se connecte sinon on close le socket et on exit
        #data = net._sock.recv(1024)
        #if int(data) < 1:
        #    print "Il n'y a plus de connexion de disponible"
        #    exit()
